### ISSUE TITLE
Cannot place bid

### ISSUE THREAD

**Issue by johnmark13** [vessenes/persona#51]
Bidding 10 Eth on https://beta.personacollective.ai/persona/33 and got this Error in console:

```
Error placing bid: Error: execution reverted (unknown custom error) (action="estimateGas", data="0x177e802f00000000000000000000000090c2f2fb3e49fd8182fdc0066824e74f70c500010000000000000000000000000000000000000000000000000000000000000021", reason=null, transaction={ "data": "0x04717aca0000000000000000000000001e8ae08b6817f27df92e3bb24604aa90d3a5672f00000000000000000000000000000000000000000000000000000000000000210000000000000000000000000000000000000000000000008ac7230489e80000", "from": "0x06820Aa850Cf12106685F87a460DDe7AcE493c6b", "to": "0x90c2f2FB3e49fd8182FdC0066824e74f70c50001" }, invocation=null, revert=null, code=CALL_EXCEPTION, version=6.13.2)
    at makeError (ethers.js?v=5d648213:325:15)
    at getBuiltinCallException (ethers.js?v=5d648213:11817:10)
    at _AbiCoder.getBuiltinCallException (ethers.js?v=5d648213:11888:12)
    at BrowserProvider.getRpcError (ethers.js?v=5d648213:19020:26)
    at BrowserProvider.getRpcError (ethers.js?v=5d648213:21428:18)
    at ethers.js?v=5d648213:19208:27
```

Had it on another 2, and all had recently be in the Vats maybe

**Comment by vessenes** [comment]
Thanks, this is interesting. 

Here are the possible reasons placeBid would revert:

        require(WETH.allowance(msg.sender, address(this)) >= price, "Insufficient WETH allowance");
        require(WETH.balanceOf(msg.sender) >= price, "Insufficient WETH balance");
        require(uiFee10k <= UIFeeMax10k, "UI Fee too high"); 

Each of those would come with an error message.

placeBid is marked nonReentrant which does not throw an error message, so it's possible the current owner of the persona is using a wallet which triggers a function in the order book, but that is extremely unlikely I think..

My guess is that this is related to the phantom asks sticking around; they follow the persona to the vats, and aren't cleared. This will be fixed in v0.2. Let's see if we can recreate it then, but I bet this won't happen again.
